<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [1]:
!pip install pandas
!pip install matplotlib

Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 97.8 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 130.1 MB/s eta 0:00:00
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
Collecting fonttools>=4.22.0 (from matplotlib)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.23 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.4.6)
Collecting pillow>=8 (from matplotlib)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 100.0 MB/s eta 0:00:00
Downloading contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 95.3 MB/s eta 0:00:00
Downloading kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 106.8 MB/s eta 0:00:00
Downloading pillow-12.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 121.8 MB/s eta 0:00:00
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [3]:
# Import necessary libraries
import pandas as pd
# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [4]:
# Write your code here
pd.set_option('display.max_rows' , None)
pd.set_option('display.max_columns' , None)
print(df.shape)
print(df.dtypes)

(65437, 114)
ResponseId                          int64
MainBranch                            str
Age                                   str
Employment                            str
RemoteWork                            str
Check                                 str
CodingActivities                      str
EdLevel                               str
LearnCode                             str
LearnCodeOnline                       str
TechDoc                               str
YearsCode                             str
YearsCodePro                          str
DevType                               str
OrgSize                               str
PurchaseInfluence                     str
BuyNewTool                            str
BuildvsBuy                            str
TechEndorse                           str
Country                               str
Currency                              str
CompTotal                         float64
LanguageHaveWorkedWith                str
LanguageWantToWorkWith                str
LanguageAdmired                       str
DatabaseHaveWorkedWith                str
DatabaseWantToWorkWith                str
DatabaseAdmired                       str
PlatformHaveWorkedWith                str
PlatformWantToWorkWith                str
PlatformAdmired                       str
WebframeHaveWorkedWith                str
WebframeWantToWorkWith                str
WebframeAdmired                       str
EmbeddedHaveWorkedWith                str
EmbeddedWantToWorkWith                str
EmbeddedAdmired                       str
MiscTechHaveWorkedWith                str
MiscTechWantToWorkWith                str
MiscTechAdmired                       str
ToolsTechHaveWorkedWith               str
ToolsTechWantToWorkWith               str
ToolsTechAdmired                      str
NEWCollabToolsHaveWorkedWith          str
NEWCollabToolsWantToWorkWith          str
NEWCollabToolsAdmired                 str
OpSysPersonal use                     str
OpSysProfessional use                 str
OfficeStackAsyncHaveWorkedWith        str
OfficeStackAsyncWantToWorkWith        str
OfficeStackAsyncAdmired               str
OfficeStackSyncHaveWorkedWith         str
OfficeStackSyncWantToWorkWith         str
OfficeStackSyncAdmired                str
AISearchDevHaveWorkedWith             str
AISearchDevWantToWorkWith             str
AISearchDevAdmired                    str
NEWSOSites                            str
SOVisitFreq                           str
SOAccount                             str
SOPartFreq                            str
SOHow                                 str
SOComm                                str
AISelect                              str
AISent                                str
AIBen                                 str
AIAcc                                 str
AIComplex                             str
AIToolCurrently Using                 str
AIToolInterested in Using             str
AIToolNot interested in Using         str
AINextMuch more integrated            str
AINextNo change                       str
AINextMore integrated                 str
AINextLess integrated                 str
AINextMuch less integrated            str
AIThreat                              str
AIEthics                              str
AIChallenges                          str
TBranch                               str
ICorPM                                str
WorkExp                           float64
Knowledge_1                           str
Knowledge_2                           str
Knowledge_3                           str
Knowledge_4                           str
Knowledge_5                           str
Knowledge_6                           str
Knowledge_7                           str
Knowledge_8                           str
Knowledge_9                           str
Frequency_1                           str
Frequency_2                           str
Frequency_3                           str
TimeSearching                         str
TimeAnswering                         str
Frustration                           str
ProfessionalTech                      str
ProfessionalCloud                     str
ProfessionalQuestion                  str
Industry                              str
JobSatPoints_1                    float64
JobSatPoints_4                    float64
JobSatPoints_5                    float64
JobSatPoints_6                    float64
JobSatPoints_7                    float64
JobSatPoints_8                    float64
JobSatPoints_9                    float64
JobSatPoints_10                   float64
JobSatPoints_11                   float64
SurveyLength                          str
SurveyEase                            str
ConvertedCompYearly               float64
JobSat                            float64
dtype: object

In [6]:
print(df.isna().sum())

ResponseId                            0
MainBranch                            0
Age                                   0
Employment                            0
RemoteWork                        10631
Check                                 0
CodingActivities                  10971
EdLevel                            4653
LearnCode                          4949
LearnCodeOnline                   16200
TechDoc                           24540
YearsCode                          5568
YearsCodePro                      13827
DevType                            5992
OrgSize                           17957
PurchaseInfluence                 18031
BuyNewTool                        20256
BuildvsBuy                        22079
TechEndorse                       21769
Country                            6507
Currency                          18753
CompTotal                         31697
LanguageHaveWorkedWith             5692
LanguageWantToWorkWith             9685
LanguageAdmired                   14565
DatabaseHaveWorkedWith            15183
DatabaseWantToWorkWith            22879
DatabaseAdmired                   26880
PlatformHaveWorkedWith            23071
PlatformWantToWorkWith            30905
PlatformAdmired                   34060
WebframeHaveWorkedWith            20276
WebframeWantToWorkWith            26902
WebframeAdmired                   30494
EmbeddedHaveWorkedWith            43223
EmbeddedWantToWorkWith            47837
EmbeddedAdmired                   48704
MiscTechHaveWorkedWith            25994
MiscTechWantToWorkWith            32473
MiscTechAdmired                   35841
ToolsTechHaveWorkedWith           12955
ToolsTechWantToWorkWith           19353
ToolsTechAdmired                  21440
NEWCollabToolsHaveWorkedWith       7845
NEWCollabToolsWantToWorkWith      13350
NEWCollabToolsAdmired             14726
OpSysPersonal use                  7263
OpSysProfessional use             12464
OfficeStackAsyncHaveWorkedWith    17344
OfficeStackAsyncWantToWorkWith    26471
OfficeStackAsyncAdmired           28233
OfficeStackSyncHaveWorkedWith      9892
OfficeStackSyncWantToWorkWith     18726
OfficeStackSyncAdmired            20725
AISearchDevHaveWorkedWith         20984
AISearchDevWantToWorkWith         28736
AISearchDevAdmired                29894
NEWSOSites                         5151
SOVisitFreq                        5901
SOAccount                          5877
SOPartFreq                        20200
SOHow                              6475
SOComm                             6274
AISelect                           4530
AISent                            19564
AIBen                             28543
AIAcc                             28135
AIComplex                         28416
AIToolCurrently Using             30365
AIToolInterested in Using         34746
AIToolNot interested in Using     41023
AINextMuch more integrated        51999
AINextNo change                   52939
AINextMore integrated             41009
AINextLess integrated             63082
AINextMuch less integrated        64289
AIThreat                          20748
AIEthics                          23889
AIChallenges                      27906
TBranch                           20960
ICorPM                            35636
WorkExp                           35779
Knowledge_1                       36773
Knowledge_2                       37416
Knowledge_3                       37342
Knowledge_4                       37407
Knowledge_5                       37557
Knowledge_6                       37573
Knowledge_7                       37659
Knowledge_8                       37679
Knowledge_9                       37802
Frequency_1                       37068
Frequency_2                       37073
Frequency_3                       37727
TimeSearching                     36526
TimeAnswering                     36593
Frustration                       37186
ProfessionalTech                  37673
ProfessionalCloud                 36946
ProfessionalQuestion              36630
Industry                          36579
JobSatPoints_1                    36113
JobSatPoints_4                    36044
JobSatPoints_5                    36026
JobSatPoints_6                    35987
JobSatPoints_7                    35989
JobSatPoints_8                    35981
JobSatPoints_9                    35981
JobSatPoints_10                   35987
JobSatPoints_11                   35992
SurveyLength                       9255
SurveyEase                         9199
ConvertedCompYearly               42002
JobSat                            36311
dtype: int64

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [7]:
# Write your code here
df.describe(include = ['number'])

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [9]:
#Inspect entire country column
df['Country'].value_counts()

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
France                                                   2110
Canada                                                   2104
Poland                                                   1534
Netherlands                                              1449
Brazil                                                   1375
Italy                                                    1341
Australia                                                1260
Spain                                                    1123
Sweden                                                   1016
Russian Federation                                        925
Switzerland                                               876
Austria                                                   791
Czech Republic                                            714
Israel                                                    604
Turkey                                                    546
Belgium                                                   526
Denmark                                                   504
Portugal                                                  470
Norway                                                    450
Romania                                                   439
Pakistan                                                  415
Iran, Islamic Republic of...                              411
China                                                     406
Mexico                                                    402
Hungary                                                   396
New Zealand                                               396
Greece                                                    389
Finland                                                   386
South Africa                                              358
Indonesia                                                 354
Argentina                                                 345
Bangladesh                                                327
Bulgaria                                                  319
Nigeria                                                   305
Viet Nam                                                  296
Japan                                                     288
Ireland                                                   270
Taiwan                                                    268
Egypt                                                     262
Slovakia                                                  248
Serbia                                                    245
Colombia                                                  217
Philippines                                               196
Croatia                                                   187
Lithuania                                                 183
Kenya                                                     180
Singapore                                                 177
Sri Lanka                                                 163
Malaysia                                                  161
Thailand                                                  147
South Korea                                               146
Hong Kong (S.A.R.)                                        146
Slovenia                                                  142
Nepal                                                     139
Chile                                                     133
United Arab Emirates                                      130
Latvia                                                    128
Estonia                                                   110
Morocco                                                    98
Belarus                                                    97
Georgia                                                    94
Uruguay                                                    94
Kazakhstan                                                 81
Algeria                                                    77
Peru                                                       75
Tunisia                                                    71
Ghana                                                      70
Venezuela, Bolivarian Republic of...                       69
Cyprus                                                     63
Uzbekistan                                                 62
Bosnia and Herzegovina                                     62
Ethiopia                                                   60
Armenia                                                    58
Republic of Korea                                          57
Saudi Arabia                                               56
Afghanistan                                                56
Ecuador                                                    54
Costa Rica                                                 54
Albania                                                    49
Dominican Republic                                         47
Lebanon                                                    46
Iraq                                                       44
Kyrgyzstan                                                 44
Nomadic                                                    43
Guatemala                                                  41
Luxembourg                                                 40
Jordan                                                     40
Paraguay                                                   39
Uganda                                                     39
Republic of Moldova                                        38
Republic of North Macedonia                                36
Bolivia                                                    32
Iceland                                                    31
Cameroon                                                   31
Syrian Arab Republic                                       30
Malta                                                      29
United Republic of Tanzania                                28
Azerbaijan                                                 27
Montenegro                                                 27
Zimbabwe                                                   26
Cuba                                                       23
Rwanda                                                     22
Cambodia                                                   22
Nicaragua                                                  21
Myanmar                                                    21
Angola                                                     20
El Salvador                                                19
Kosovo                                                     18
Panama                                                     18
Yemen                                                      18
Maldives                                                   16
Honduras                                                   16
Palestine                                                  15
Mauritius                                                  15
Zambia                                                     15
Andorra                                                    15
Qatar                                                      15
Madagascar                                                 14
Côte d'Ivoire                                              14
Isle of Man                                                13
Malawi                                                     12
Jamaica                                                    11
Benin                                                      11
Turkmenistan                                               11
Bahrain                                                    11
Mongolia                                                   10
Senegal                                                     9
Somalia                                                     9
Togo                                                        9
Kuwait                                                      8
Trinidad and Tobago                                         8
Oman                                                        8
Congo, Republic of the...                                   8
Tajikistan                                                  7
Sudan                                                       7
Mozambique                                                  7
Barbados                                                    6
Namibia                                                     5
Mauritania                                                  5
Botswana                                                    5
Suriname                                                    5
Cape Verde                                                  5
Antigua and Barbuda                                         5
Liechtenstein                                               4
Fiji                                                        4
Gabon                                                       4
Bahamas                                                     4
Lao People's Democratic Republic                            4
Swaziland                                                   4
Burkina Faso                                                4
Libyan Arab Jamahiriya                                      4
Liberia                                                     4
San Marino                                                  3
Democratic Republic of the Congo                            3
Burundi                                                     3
Sierra Leone                                                3
North Korea                                                 3
Guyana                                                      3
Brunei Darussalam                                           3
Bhutan                                                      3
Monaco                                                      3
Democratic People's Republic of Korea                       2
Guinea-Bissau                                               2
Belize                                                      2
Mali                                                        2
Dominica                                                    1
Papua New Guinea                                            1
Central African Republic                                    1
Equatorial Guinea                                           1
Guinea                                                      1
Niger                                                       1
Samoa                                                       1
Lesotho                                                     1
Saint Kitts and Nevis                                       1
Micronesia, Federated States of...                          1
Haiti                                                       1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, dtype: int64

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [10]:
## Looks like there are multiple different entries for north/south korea under different names
df['Country'][df['Country'].str.contains('korea' , case = False , na = False)].unique()

<ArrowStringArray>
[                    'Republic of Korea',
                           'South Korea',
                           'North Korea',
 'Democratic People's Republic of Korea']
Length: 4, dtype: str

In [11]:
#standardize formatting
df['Country'] = df['Country'].str.strip().str.lower()

#replace inconsistent names for south korea
df['Country'] = df['Country'].replace({'republic of korea' : 'south korea' , "democratic people's republic of korea" : 'north korea'})

#check it worked
df['Country'][df['Country'].str.contains('korea' , case = False , na = False)].unique()

<ArrowStringArray>
['south korea', 'north korea']
Length: 2, dtype: str

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [12]:
## Write your code here
employment_encoded = pd.get_dummies(df['Employment'] , dtype = int)
employment_encoded.head()

,"Employed, full-time","Employed, full-time;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed","Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time;Retired","Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work","Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Retired","Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired","Employed, full-time;Not employed, and not looking for work","Employed, full-time;Not employed, but looking for work","Employed, full-time;Not employed, but looking for work;Employed, part-time","Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed","Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time","Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time","Employed, full-time;Not employed, but looking for work;Not employed, and not looking for work;Employed, part-time","Employed, full-time;Not employed, but looking for work;Student, part-time","Employed, full-time;Retired","Employed, full-time;Student, full-time","Employed, full-time;Student, full-time;Employed, part-time","Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed","Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time","Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time","Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired","Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired","Employed, full-time;Student, full-time;Not employed, but looking for work","Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed","Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time","Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Employed, part-time","Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Employed, part-time;Retired","Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time","Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired","Employed, full-time;Student, full-time;Not employed, but looking for work;Student, part-time","Employed, full-time;Student, full-time;Not employed, but looking for work;Student, part-time;Employed, part-time","Employed, full-time;Student, full-time;Student, part-time","Employed, full-time;Student, full-time;Student, part-time;Employed, part-time","Employed, full-time;Student, part-time","Employed, full-time;Student, part-time;Employed, part-time","Employed, part-time","Employed, part-time;Retired",I prefer not to say,"Independent contractor, freelancer, or self-employed","Independent contractor, freelancer, or self-employed;Employed, part-time","Independent contractor, freelancer, or self-employed;Employed, part-time;Retired","Independent contractor, freelancer, or self-employed;Not employed, and not looking for work","Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time","Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Retired","Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time","Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Retired","Independent contractor, freelancer, or self-employed;Retired","Independent contractor, freelancer, or self-employed;Student, part-time","Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time","Independent contractor, freelancer, or self-employed;Student, part-time;Retired","Not employed, and not looking for work","Not employed, and not looking for work;Employed, part-time","Not employed, and not looking for work;Retired","Not employed, and not looking for work;Student, part-time","Not employed, and not looking for work;Student, part-time;Employed, part-time","Not employed, but looking for work","Not employed, but looking for work;Employed, part-time","Not employed, but looking for work;Independent contractor, freelancer, or self-employed","Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time","Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work","Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time","Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Retired","Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Retired","Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time","Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time","Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Retired","Not employed, but looking for work;Not employed, and not looking for work","Not employed, but looking for work;Not employed, and not looking for work;Student, part-time","Not employed, but looking for work;Not employed, and not looking for work;Student, part-time;Employed, part-time","Not employed, but looking for work;Retired","Not employed, but looking for work;Student, part-time","Not employed, but looking for work;Student, part-time;Employed, part-time","Not employed, but looking for work;Student, part-time;Retired",Retired,"Student, full-time","Student, full-time;Employed, part-time","Student, full-time;Independent contractor, freelancer, or self-employed","Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time","Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time;Retired","Student, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work","Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time","Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time","Student, full-time;Not employed, and not looking for work","Student, full-time;Not employed, and not looking for work;Employed, part-time","Student, full-time;Not employed, and not looking for work;Student, part-time","Student, full-time;Not employed, but looking for work","Student, full-time;Not employed, but looking for work;Employed, part-time","Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed","Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time","Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work","Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time","Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time","Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired","Student, full-time;Not employed, but looking for work;Not employed, and not looking for work","Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time","Student, full-time;Not employed, but looking for work;Retired","Student, full-time;Not employed, but looking for work;Student, part-time","Student, full-time;Retired","Student, full-time;Student, part-time","Student, full-time;Student, part-time;Employed, part-time","Student, full-time;Student, part-time;Retired","Student, part-time","Student, part-time;Employed, part-time","Student, part-time;Retired"
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [14]:
## Write your code here
df.isna().sum().sort_values(ascending = False)

AINextMuch less integrated        64289
AINextLess integrated             63082
AINextNo change                   52939
AINextMuch more integrated        51999
EmbeddedAdmired                   48704
EmbeddedWantToWorkWith            47837
EmbeddedHaveWorkedWith            43223
ConvertedCompYearly               42002
AIToolNot interested in Using     41023
AINextMore integrated             41009
Knowledge_9                       37802
Frequency_3                       37727
Knowledge_8                       37679
ProfessionalTech                  37673
Knowledge_7                       37659
Knowledge_6                       37573
Knowledge_5                       37557
Knowledge_2                       37416
Knowledge_4                       37407
Knowledge_3                       37342
Frustration                       37186
Frequency_2                       37073
Frequency_1                       37068
ProfessionalCloud                 36946
Knowledge_1                       36773
ProfessionalQuestion              36630
TimeAnswering                     36593
Industry                          36579
TimeSearching                     36526
JobSat                            36311
JobSatPoints_1                    36113
JobSatPoints_4                    36044
JobSatPoints_5                    36026
JobSatPoints_11                   35992
JobSatPoints_7                    35989
JobSatPoints_6                    35987
JobSatPoints_10                   35987
JobSatPoints_8                    35981
JobSatPoints_9                    35981
MiscTechAdmired                   35841
WorkExp                           35779
ICorPM                            35636
AIToolInterested in Using         34746
PlatformAdmired                   34060
MiscTechWantToWorkWith            32473
CompTotal                         31697
PlatformWantToWorkWith            30905
WebframeAdmired                   30494
AIToolCurrently Using             30365
AISearchDevAdmired                29894
AISearchDevWantToWorkWith         28736
AIBen                             28543
AIComplex                         28416
OfficeStackAsyncAdmired           28233
AIAcc                             28135
AIChallenges                      27906
WebframeWantToWorkWith            26902
DatabaseAdmired                   26880
OfficeStackAsyncWantToWorkWith    26471
MiscTechHaveWorkedWith            25994
TechDoc                           24540
AIEthics                          23889
PlatformHaveWorkedWith            23071
DatabaseWantToWorkWith            22879
BuildvsBuy                        22079
TechEndorse                       21769
ToolsTechAdmired                  21440
AISearchDevHaveWorkedWith         20984
TBranch                           20960
AIThreat                          20748
OfficeStackSyncAdmired            20725
WebframeHaveWorkedWith            20276
BuyNewTool                        20256
SOPartFreq                        20200
AISent                            19564
ToolsTechWantToWorkWith           19353
Currency                          18753
OfficeStackSyncWantToWorkWith     18726
PurchaseInfluence                 18031
OrgSize                           17957
OfficeStackAsyncHaveWorkedWith    17344
LearnCodeOnline                   16200
DatabaseHaveWorkedWith            15183
NEWCollabToolsAdmired             14726
LanguageAdmired                   14565
YearsCodePro                      13827
NEWCollabToolsWantToWorkWith      13350
ToolsTechHaveWorkedWith           12955
OpSysProfessional use             12464
CodingActivities                  10971
RemoteWork                        10631
OfficeStackSyncHaveWorkedWith      9892
LanguageWantToWorkWith             9685
SurveyLength                       9255
SurveyEase                         9199
NEWCollabToolsHaveWorkedWith       7845
OpSysPersonal use                  7263
Country                            6507
SOHow                              6475
SOComm                             6274
DevType                            5992
SOVisitFreq                        5901
SOAccount                          5877
LanguageHaveWorkedWith             5692
YearsCode                          5568
NEWSOSites                         5151
LearnCode                          4949
EdLevel                            4653
AISelect                           4530
MainBranch                            0
Age                                   0
Employment                            0
Check                                 0
ResponseId                            0
dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [15]:
## Write your code here
print('missing values:' , df['ConvertedCompYearly'].isna().sum())
ConvertedCompYearly_median = df['ConvertedCompYearly'].median()
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(ConvertedCompYearly_median)
df['ConvertedCompYearly'].head()
print('missing values filled with median:' , df['ConvertedCompYearly'].isna().sum())

missing values: 42002
missing values filled with median: 0

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [16]:
## Write your code here
print('missing values:' , df['RemoteWork'].isna().sum())
remotework_mode = df['RemoteWork'].mode()[0]
df['RemoteWork'] = df['RemoteWork'].fillna(remotework_mode)
print('missing values filled with mode:' , df['RemoteWork'].isna().sum())

missing values: 10631
missing values filled with mode: 0

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [18]:
## Write your code here
min_compy = df['ConvertedCompYearly'].min()
max_compy = df['ConvertedCompYearly'].max()
df['ConvertedCompYearly_MinMax'] = (df['ConvertedCompYearly'] - min_compy) / (max_compy - min_compy)
df['ConvertedCompYearly_MinMax'].head()

0    0.003998
1    0.003998
2    0.003998
3    0.003998
4    0.003998
Name: ConvertedCompYearly_MinMax, dtype: float64

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [20]:
## Write your code here
import numpy as np
df['ConvertedCompYearly_log'] = np.log(df['ConvertedCompYearly'])
df['ConvertedCompYearly_log'].head()

0    11.082143
1    11.082143
2    11.082143
3    11.082143
4    11.082143
Name: ConvertedCompYearly_log, dtype: float64

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [21]:
##column has numbers stored as strings, and inconsistent values like 'less than 1 year' so we need to clean the column first.
df['YearsCodePro'].unique()

<ArrowStringArray>
[                 nan,                 '17',                 '27',
                  '7',                 '11',                 '25',
                 '12',                 '10',                  '3',
   'Less than 1 year',                 '18',                 '37',
                 '15',                 '20',                  '6',
                  '2',                 '16',                  '8',
                 '14',                  '4',                 '45',
                  '1',                 '24',                 '29',
                  '5',                 '30',                 '26',
                  '9',                 '33',                 '13',
                 '35',                 '23',                 '22',
                 '31',                 '19',                 '21',
                 '28',                 '34',                 '32',
                 '40',                 '50',                 '39',
                 '44',                 '42',                 '41',
                 '36',                 '38', 'More than 50 years',
                 '43',                 '47',                 '48',
                 '46',                 '49']
Length: 53, dtype: str

In [28]:
#replace inconsistent values
df['YearsCodePro'] = df['YearsCodePro'].replace({'Less than 1 year' : 0.5 , 'More than 50 years' : 51})

#convert to numeric values
df['YearsCodePro'] = pd.to_numeric(df['YearsCodePro'] , errors = 'coerce')

#fill in missing values
yearscodepro_median = df['YearsCodePro'].median()
df['YearsCodePro'] = df['YearsCodePro'].fillna(yearscodepro_median)
print('missing values:' , df['YearsCodePro'].isna().sum())

missing values: 0

In [30]:
#create 'ExperienceLevel' column by turning years coded into 3 bins representing experience levels
bins = [0 , 3 , 10 , 100]
labels = ['entry-level' , 'mid-level' , 'senior-level']
df['ExperienceLevel'] = pd.cut(df['YearsCodePro'] , bins = bins , labels = labels)

df['ExperienceLevel'].value_counts()

ExperienceLevel
mid-level       33221
senior-level    18460
entry-level     13756
Name: count, dtype: int64

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.